global:
  scrape_interval:     15s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: [localhost:9090]

  - job_name: mysqld_exporter
    scrape_interval: 5s
    static_configs:
      - targets: [10.110.0.3:9104]

  - job_name: advisor_exporter
    scrape_interval: 5s
    static_configs:
      - targets: [10.110.0.3:8080]

  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
      - targets: [10.110.0.3:9100]
